kind: Service
apiVersion: v1
metadata:
  name: config-kubernetes
spec:
  selector:
    app: config-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30084
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-kubernetes
  namespace: default
spec:
  selector:
    matchLabels:
      app: config-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: config-kubernetes
    spec:
      containers:
        - name: config-kubernetes
          image: shalmali85/config-kubernetes:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


