---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: config-kubernetes
rules:
  - apiGroups: [ "", "extensions", "apps" ] # "" indicates the core API group
    resources: [ "configmaps", "pods", "services", "endpoints", "secrets" ]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: config-kubernetes
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: config-example
  apiGroup: rbac.authorization.k8s.io